name: Node.js CI ZTE Simulator

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x] # Test on multiple Node versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      # - name: Run Prettier check (optional, if lint doesn't cover it)
      #   run: npm run prettier

      - name: Run tests
        run: npm test

      # Optional: Run Postman tests if the server can be started in CI
      # This might require starting the server in the background
      # - name: Start server in background
      #   run: npm start &
      #   env:
      #     CI: true # Your server might need this
      # - name: Wait for server to start
      #   run: sleep 5 # Adjust as needed
      # - name: Run Postman tests with Newman
      #   run: npm run postman:run
      # - name: Stop server
      #   run: pkill node || true # Kill the server process

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Optional: if you use Codecov
          files: ./coverage/clover.xml,./coverage/lcov.info # Adjust based on your coverage reporters
          fail_ci_if_error: true
